# Generated by Django 5.2.12 on 2026-04-07 17:56
import logging

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

from sentry.new_migrations.migrations import CheckedMigration
from sentry.utils.query import bulk_delete_objects

logger = logging.getLogger(__name__)


def delete_redundant_error_detector_workflows(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    """
    Delete DetectorWorkflow rows where:
    1. The detector type is "error"
    2. There exists another DetectorWorkflow with the same workflow_id
       connected to an "issue_stream" detector

    Uses batched deletion (10k rows at a time) for efficiency with ~2.4M rows.
    """
    Detector = apps.get_model("workflow_engine", "Detector")
    DetectorWorkflow = apps.get_model("workflow_engine", "DetectorWorkflow")

    # Get error detector IDs (one per project)
    error_detector_ids = set(Detector.objects.filter(type="error").values_list("id", flat=True))

    # Get workflow IDs that have issue_stream detector connections
    issue_stream_detector_ids = Detector.objects.filter(type="issue_stream").values_list(
        "id", flat=True
    )
    issue_stream_workflow_ids = set(
        DetectorWorkflow.objects.filter(detector_id__in=issue_stream_detector_ids).values_list(
            "workflow_id", flat=True
        )
    )

    logger.info(
        "Starting deletion of redundant error detector workflows",
        extra={
            "error_detector_count": len(error_detector_ids),
            "issue_stream_workflow_count": len(issue_stream_workflow_ids),
        },
    )

    # Delete in batches using bulk_delete_objects
    while bulk_delete_objects(
        DetectorWorkflow,
        logger=logger,
        detector_id__in=error_detector_ids,
        workflow_id__in=issue_stream_workflow_ids,
    ):
        pass


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = True

    dependencies = [
        ("workflow_engine", "0111_add_workflowfirehistory_date_added_index"),
    ]

    operations = [
        migrations.RunPython(
            delete_redundant_error_detector_workflows,
            migrations.RunPython.noop,
            hints={
                "tables": [
                    "workflow_engine_detector",
                    "workflow_engine_detectorworkflow",
                ]
            },
        ),
    ]
